// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdzyfcdprrirgkhzyhoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkenlmY2RwcnJpcmdraHp5aG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTU1NTAsImV4cCI6MjA2MDg5MTU1MH0.X8mkkM-63zVSMzS1c8YERiwQS06OyF0GqP3kPI9ZDgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);